# version format
version: 2.3.0.{build}

# branches to build
branches:
  # only build master
  only:
    - master

# build Release	
configuration: Release

# restore NuGet packages before building
before_build:
- nuget restore

# sigh *zip*
after_build:
- 7z a LegendaryClient.zip LegendaryClient\bin\Release
- move LegendaryClient\bin\Release\Client\LegendaryClient.exe LegendaryClient.exe

# define solution file
build:
  project: LegendaryClient.sln
  # shut up
  verbosity: minimal

artifacts:
  - path: LegendaryClient.zip
    name: LegendaryClient-Full
  - path: LegendaryClient.exe
    name: LegendaryClient-Executable

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/bda62727b7b80a130d60
